[package]
name = "pam_viewer_renderer"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[features]
default = ["web-host"]
web-host = []

[dependencies]
bytemuck.workspace = true
futures-channel.workspace = true
pam_viewer_core = { path = "../core" }
parking_lot.workspace = true
serde.workspace = true
thiserror.workspace = true
wgpu.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
pollster = "1"
rayon.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
futures-util = "0.3"
gloo-timers = { version = "0.3", features = ["futures"] }
js-sys = "0.3"
console_error_panic_hook = "0.1"
serde-wasm-bindgen = "0.6"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = [
    "Document",
    "Element",
    "HtmlCanvasElement",
    "OffscreenCanvas",
    "Window",
] }

[dev-dependencies]
pam_viewer_formats = { path = "../formats" }
pollster = "1"
